import AppError from '../utils/appError';

// Handles invalid json-webtoken error
const handleTokenError = (e: Error) => {
    return new AppError('Invalid token... please login again', 401);
};

// Express Error Handler
export default (
    err: any,
    req: ExpressTypes.Request,
    res: ExpressTypes.Response,
    next: ExpressTypes.NextFn
) => {
    err.statusCode = err.statusCode || 500;
    err.status = err.status || 'error';

    // If the current environment is development send the entire error and error stack as JSON response to the user in case of an error
    if (process.env.NODE_ENV === 'development') {
        return res.status(err.statusCode).json({
            error: err,
            status: err.status,
            stack: err.stack,
            message: err.message,
        });
    }
    // If the current environment is production then send only the status : success | fail and the message to the user in case of an error
    else if (process.env.NODE_ENV === 'production') {
        if (err.name === 'JsonWebTokenError') err = handleTokenError(err);
        
        // isOperational field indicates the error is generated by the application (AppError class)
        if (err.isOperational) {
            return res.status(err.statusCode).json({
                message: err.message,
                status: err.status,
            });
        }
        // If the error is not generated by the application then log the error
        else {
            console.log(err);
            return res.status(500).json({
                error: 'error',
                message: 'Something went wrong',
            });
        }
    }
};
